### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by KingTino104** [Quarris/TwerkCropGrowth#2]

**Comment by KingTino104** [comment]
https://github.com/Quarris/TwerkCropGrowth/assets/90916297/3f57bc79-8e32-49c8-a689-2b71d76cee7c

**Comment by Quarris** [comment]
🤣 Music added for effect? Amazing xD

I don't know of any issues that might be causing this. Did you change configs at all? Maybe try increasing the frequency to see if that an issue.
I will double check on a fresh instance to be safe as well.

**Comment by Quarris** [comment]
Yeah I would say the default configs might be a bit too low but it is working. Can you increase the chance and max blocks in the configs and see if it helps?

**Comment by KingTino104** [comment]
sure, btw i didnt change anything and i wouldn't have made an issue if i changed something

**Comment by KingTino104** [comment]
> 🤣 Music added for effect? Amazing xD
> 
> I don't know of any issues that might be causing this. Did you change configs at all? Maybe try increasing the frequency to see if that an issue. I will double check on a fresh instance to be safe as well.

lol i had that song on obs for some reason so i just turned it on idk why

**Comment by KingTino104** [comment]
sry if im being dumb or annoying but idk how to config it bcuz idk how to make a custom config file and your mod dosent make one at startup.

**Comment by Quarris** [comment]
That's because they are server configs. Close your game and go into the world save folder. In there there will be a serverconfigs folder which contains the twerkcropgrowth config file

**Comment by KingTino104** [comment]
thanks
